// Central FontAwesome registry. Import this once (in main.tsx) so all icons are available by name,
// e.g. <FontAwesomeIcon icon="gear" />. The @fortawesome/* packages are installed npm dependencies.
import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faArrowDown,
  faArrowUp,
  faBook,
  faChartColumn,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faCircleCheck,
  faCircleQuestion,
  faCircleXmark,
  faDumbbell,
  faEnvelope,
  faEye,
  faForward,
  faGear,
  faGraduationCap,
  faMagnifyingGlass,
  faSkull,
  faSpinner,
  faTrashCan,
  faVolumeHigh,
  faXmark,
} from '@fortawesome/free-solid-svg-icons'

library.add(
  faArrowDown,
  faArrowUp,
  faBook,
  faChartColumn,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faCircleCheck,
  faCircleQuestion,
  faCircleXmark,
  faDumbbell,
  faEnvelope,
  faEye,
  faForward,
  faGear,
  faGraduationCap,
  faMagnifyingGlass,
  faSkull,
  faSpinner,
  faTrashCan,
  faVolumeHigh,
  faXmark,
)
