// Pre-builds the static content payloads for the no-backend demo — `npm run gen:content`.
// The JA payload mirrors GET /api/content exactly (same loader, same JSON the web static build fetches
// at runtime). The AR payload is built from the Arabic root/sentence CSVs. Both are consumed by the
// mobile app; the web app reads only content.json (JA). Regenerated by `npm run build:static`.
import { mkdir, writeFile } from 'node:fs/promises'
import { getContent } from '../server/content'
import { loadArContent } from '../server/content.ar'

const OUT_DIR = new URL('../public/', import.meta.url)

async function main() {
  await mkdir(OUT_DIR, { recursive: true })

  // Japanese — the web app + server share this exact payload (content.json, no lang field → defaults to ja).
  const { units, sentences, kanjiMeanings, kanjiRadicals, kanjiComponents } = await getContent()
  const ja = { units, sentences, kanjiMeanings, kanjiRadicals, kanjiComponents }
  await writeFile(new URL('content.json', OUT_DIR), JSON.stringify(ja), 'utf8')

  // Arabic — mobile-only for now (content.ar.json).
  const ar = await loadArContent()
  await writeFile(new URL('content.ar.json', OUT_DIR), JSON.stringify(ar), 'utf8')

  console.log(
    `[gen:content] wrote ja: ${units.length} units, ${sentences.length} sentences → public/content.json`,
  )
  console.log(
    `[gen:content] wrote ar: ${ar.units.length} units, ${ar.sentences.length} sentences → public/content.ar.json`,
  )
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
